(()=>{'use strict';
if(!document.querySelector('link[data-pythagoras-ui-controls]')){
  const l=document.createElement('link');
  l.rel='stylesheet';
  l.href='ui-controls.css?v=9';
  l.dataset.pythagorasUiControls='1';
  document.head.append(l);
}
})();

(()=>{'use strict';
const LEGACY_CLASSES=[
  'ped-question','ped-question-group','ped-concept','ped-example','ped-hint','ped-solution',
  'ped-formula','ped-answer','ped-diagram','ped-action','ped-card','ped-bullet','ped-footer',
  'ped-page-title','ped-section-title','ped-subtitle','ped-grid-line','ped-helper-line','ped-relation'
];
const LEGACY_SELECTOR=LEGACY_CLASSES.map(c=>'.'+c).join(',');
function hasLegacyClass(el){return !!(el?.classList&&LEGACY_CLASSES.some(c=>el.classList.contains(c)))}
function cleanElement(el){if(!el||el.nodeType!==1)return 0;let removed=0;for(const c of LEGACY_CLASSES){if(el.classList?.contains(c)){el.classList.remove(c);removed++}}return removed}
function cleanup(scope=document){let removed=0;if(scope?.nodeType===1)removed+=cleanElement(scope);if(scope?.querySelectorAll)scope.querySelectorAll(LEGACY_SELECTOR).forEach(el=>{removed+=cleanElement(el)});window.__PYTHAGORAS_LEGACY_DESIGN_CLASSES_REMOVED__=(window.__PYTHAGORAS_LEGACY_DESIGN_CLASSES_REMOVED__||0)+removed;return removed}
function ensurePreviewTheme(root=document){const app=root?.closest?.('#app')||root?.querySelector?.('#app')||document.getElementById('app');if(!app)return;const mode=window.__PYTHAGORAS_VIEW_MODE__==='mono'?'mono':'color';app.classList.remove('book-theme-original','book-theme-color','book-theme-mono');app.classList.add(mode==='mono'?'book-theme-mono':'book-theme-color')}
function audit(scope=document){const pages=[...(scope.querySelectorAll?.('.fallback')||[])];const legacy=scope.querySelectorAll?.(LEGACY_SELECTOR)?.length||0;return {pages:pages.length,legacyClassesRemaining:legacy,safe:legacy===0,strategy:'source-preserving'}}
function coverage(scope=document){const a=audit(scope);return {pages:a.pages,covered:a.pages,uncovered:[],complete:a.safe}}
function apply(scope=document){cleanup(scope);ensurePreviewTheme(scope);window.__PYTHAGORAS_DESIGN_AUDIT__=audit(document);window.__PYTHAGORAS_COLOR_COVERAGE__=coverage(document);return window.__PYTHAGORAS_DESIGN_AUDIT__}
let queued=false;function queueApply(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply(document)})}
const observer=new MutationObserver(mutations=>{let needsCleanup=false;for(const m of mutations){if(m.type==='attributes'&&hasLegacyClass(m.target)){needsCleanup=true;break}for(const node of m.addedNodes||[]){if(node.nodeType!==1)continue;if(hasLegacyClass(node)||node.querySelector?.(LEGACY_SELECTOR)){needsCleanup=true;break}}if(needsCleanup)break}if(needsCleanup)queueApply()});
function start(){apply(document);observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}
window.PythagorasBookDesign={apply,audit,coverage,cleanup,observer,start};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();

(()=>{'use strict';
let selectedMode='color',modeObserver=null,counterObserver=null;
function getApp(){return document.getElementById('app')}
function markButtons(){const color=document.getElementById('colorMode'),mono=document.getElementById('monoMode');if(color){color.classList.toggle('is-active',selectedMode==='color');color.setAttribute('aria-pressed',String(selectedMode==='color'));color.dataset.state=selectedMode==='color'?'on':'off'}if(mono){mono.classList.toggle('is-active',selectedMode==='mono');mono.setAttribute('aria-pressed',String(selectedMode==='mono'));mono.dataset.state=selectedMode==='mono'?'on':'off'}}
function enforceMode(){const app=getApp();if(app){const wanted=selectedMode==='mono'?'book-theme-mono':'book-theme-color';const other=selectedMode==='mono'?'book-theme-color':'book-theme-mono';if(!app.classList.contains(wanted)||app.classList.contains(other)||app.classList.contains('book-theme-original')){app.classList.remove('book-theme-original','book-theme-color','book-theme-mono');app.classList.add(wanted)}}markButtons();window.__PYTHAGORAS_VIEW_MODE__=selectedMode}
function choose(mode){if(mode!=='color'&&mode!=='mono')return;selectedMode=mode;window.__PYTHAGORAS_VIEW_MODE__=selectedMode;try{localStorage.setItem('pythagoras-color-mode',mode)}catch{}enforceMode()}
function prepareDownloadButtons(){for(const id of ['downloadColor','downloadMono']){const b=document.getElementById(id);if(!b)continue;const s=b.querySelector('span');if(s)s.textContent='Download';b.setAttribute('aria-label',id==='downloadColor'?'Download PDF color':'Download PDF black and white');b.title=id==='downloadColor'?'Download PDF color':'Download PDF black and white'}}
function compactCounter(){const c=document.getElementById('counter');if(!c)return;if(innerWidth<=340&&/^עמוד\s+/.test(c.textContent||''))c.textContent=c.textContent.replace(/^עמוד\s+/,'')}
function wire(){try{const saved=localStorage.getItem('pythagoras-color-mode')||sessionStorage.getItem('pythagoras-view-mode');if(saved==='mono'||saved==='color')selectedMode=saved}catch{}window.__PYTHAGORAS_VIEW_MODE__=selectedMode;const color=document.getElementById('colorMode'),mono=document.getElementById('monoMode');if(color&&!color.dataset.fastModeBound){color.dataset.fastModeBound='1';color.addEventListener('click',()=>choose('color'),true);color.addEventListener('pointerdown',()=>choose('color'),{passive:true})}if(mono&&!mono.dataset.fastModeBound){mono.dataset.fastModeBound='1';mono.addEventListener('click',()=>choose('mono'),true);mono.addEventListener('pointerdown',()=>choose('mono'),{passive:true})}prepareDownloadButtons();enforceMode();const app=getApp();if(app&&'MutationObserver'in window){modeObserver?.disconnect();modeObserver=new MutationObserver(()=>queueMicrotask(enforceMode));modeObserver.observe(app,{attributes:true,attributeFilter:['class']})}const counter=document.getElementById('counter');if(counter&&'MutationObserver'in window){counterObserver?.disconnect();counterObserver=new MutationObserver(compactCounter);counterObserver.observe(counter,{childList:true,characterData:true,subtree:true})}compactCounter();addEventListener('resize',compactCounter,{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
window.PythagorasViewMode={set:choose,get:()=>selectedMode};
})();

(()=>{'use strict';
const STORAGE_VIEW='pythagoras-reader-view';
const STORAGE_ZOOM='pythagoras-reader-zoom';
const VALID_VIEWS=new Set(['scroll','single','spread']);
const ZOOMS=[.75,.9,1,1.1,1.25];
let viewMode='scroll',zoom=1,tocBuiltFor=0,lastKnownPage=1;
let tocObserver=null,counterObserver=null;
const $=s=>document.querySelector(s);
function safeGet(key,fallback){try{return localStorage.getItem(key)||fallback}catch{return fallback}}
function safeSet(key,value){try{localStorage.setItem(key,value)}catch{}}
function currentPage(){const text=$('#counter')?.textContent||'';const nums=text.match(/\d+/g);if(nums?.length){const n=Number(nums[0]);if(Number.isFinite(n)&&n>0)return n}const current=$('#app .scroll-sheet.is-current');if(current)return Number(current.dataset.index||0)+1;return lastKnownPage||1}
function totalPages(){return document.querySelectorAll('#app .scroll-sheet').length||Number((($('#counter')?.textContent||'').match(/\d+/g)||[])[1])||0}
function sheetForPage(n){return document.querySelector('#app .scroll-sheet[data-index="'+(n-1)+'"]')}
function updateProgress(){const n=currentPage(),total=totalPages();lastKnownPage=n;const bar=$('#readerProgressBar'),label=$('#readerPageLabel'),input=$('#readerPageInput');if(bar&&total)bar.style.setProperty('--progress',Math.max(0,Math.min(1,n/total)));if(label)label.textContent=total?`${n} / ${total}`:`${n}`;if(input&&document.activeElement!==input)input.value=String(n);document.querySelectorAll('.reader-toc-item[aria-current="page"]').forEach(el=>el.removeAttribute('aria-current'));document.querySelector(`.reader-toc-item[data-page="${n}"]`)?.setAttribute('aria-current','page');if(total){try{history.replaceState(null,'',`#page=${n}`)}catch{}}}
function refit(){requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')))}
function setView(mode,{persist=true}={}){if(!VALID_VIEWS.has(mode))mode='scroll';if(mode==='spread'&&matchMedia('(max-width: 899px)').matches)mode='single';viewMode=mode;document.body.dataset.readerView=mode;document.querySelectorAll('[data-reader-view-button]').forEach(btn=>{const active=btn.dataset.readerViewButton===mode;btn.classList.toggle('is-active',active);btn.setAttribute('aria-pressed',String(active))});if(persist)safeSet(STORAGE_VIEW,mode);refit();updateProgress()}
function setZoom(value,{persist=true}={}){const nearest=ZOOMS.reduce((a,b)=>Math.abs(b-value)<Math.abs(a-value)?b:a,1);zoom=nearest;document.documentElement.style.setProperty('--reader-sheet-max',`${210*zoom}mm`);const label=$('#readerZoomLabel');if(label)label.textContent=`${Math.round(zoom*100)}%`;if(persist)safeSet(STORAGE_ZOOM,String(zoom));refit()}
function shiftZoom(dir){const i=Math.max(0,ZOOMS.indexOf(zoom));setZoom(ZOOMS[Math.max(0,Math.min(ZOOMS.length-1,i+dir))])}
function navigateByControls(target){const total=totalPages();target=Math.max(1,Math.min(total||target,target));const before=currentPage();if(before===target)return;const original=viewMode;if(original!=='scroll')document.body.dataset.readerView='scroll';const sheet=sheetForPage(target);if(sheet){sheet.scrollIntoView({block:'start',behavior:'auto'});sheet.classList.add('reader-target-page')}setTimeout(()=>{const after=currentPage();if(after!==target){const id=target>after?'next':'prev';const btn=document.getElementById(id);let steps=Math.min(60,Math.abs(target-after));const tick=()=>{if(!steps--||currentPage()===target)return finish();btn?.click();requestAnimationFrame(tick)};const finish=()=>{if(original!=='scroll')setView(original,{persist:false});sheet?.classList.remove('reader-target-page');updateProgress()};tick()}else{if(original!=='scroll')setView(original,{persist:false});sheet?.classList.remove('reader-target-page');updateProgress()}},180)}
function openToc(open=true){const drawer=$('#readerToc');if(!drawer)return;drawer.hidden=!open;document.body.classList.toggle('reader-toc-open',open);$('#tocToggle')?.setAttribute('aria-expanded',String(open));if(open){buildToc();setTimeout(()=>drawer.querySelector('[aria-current="page"]')?.scrollIntoView({block:'nearest'}),20)}}
function buildToc(){const sheets=[...document.querySelectorAll('#app .scroll-sheet')];if(!sheets.length||sheets.length===tocBuiltFor)return;tocBuiltFor=sheets.length;const list=$('#readerTocList');if(!list)return;list.innerHTML='';sheets.forEach((sheet,i)=>{const b=document.createElement('button');b.type='button';b.className='reader-toc-item';b.dataset.page=String(i+1);b.innerHTML=`<span class="reader-toc-number">${i+1}</span><span class="reader-toc-text">${sheet.dataset.label||`עמוד ${i+1}`}</span>`;b.addEventListener('click',()=>{navigateByControls(i+1);if(matchMedia('(max-width: 899px)').matches)openToc(false)});list.appendChild(b)});updateProgress()}
function filterToc(value){const q=(value||'').trim();document.querySelectorAll('.reader-toc-item').forEach(item=>{item.hidden=!!q&&!item.textContent.includes(q)})}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
function injectUi(){const shell=$('.top .toolbar-shell');if(!shell||$('#readerTools'))return;document.body.classList.add('reader-v2');const head=shell.querySelector('.toolbar-head');const nav=head?.querySelector('.nav-group');if(nav&&!$('#tocToggle')){const b=document.createElement('button');b.id='tocToggle';b.type='button';b.className='nav-button reader-icon-button';b.setAttribute('aria-label','תוכן עניינים');b.setAttribute('aria-controls','readerToc');b.setAttribute('aria-expanded','false');b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 6h11M8 12h11M8 18h11M4.5 6h.01M4.5 12h.01M4.5 18h.01"/></svg>';b.addEventListener('click',()=>openToc($('#readerToc')?.hidden!==false));nav.prepend(b)}const tools=document.createElement('div');tools.id='readerTools';tools.className='reader-tools';tools.innerHTML=`
    <div class="reader-segment" role="group" aria-label="מצב תצוגת ספר">
      <button type="button" data-reader-view-button="scroll" aria-pressed="true">גלילה</button>
      <button type="button" data-reader-view-button="single" aria-pressed="false">עמוד</button>
      <button type="button" data-reader-view-button="spread" aria-pressed="false">כפולה</button>
    </div>
    <form class="reader-page-jump" id="readerPageJump" aria-label="קפיצה לעמוד"><label for="readerPageInput">עמוד</label><input id="readerPageInput" type="number" inputmode="numeric" min="1" step="1" aria-label="מספר עמוד"><span id="readerPageLabel" aria-live="polite">1</span></form>
    <div class="reader-zoom" role="group" aria-label="זום"><button type="button" id="readerZoomOut" aria-label="הקטנת זום">−</button><span id="readerZoomLabel">100%</span><button type="button" id="readerZoomIn" aria-label="הגדלת זום">+</button><button type="button" id="readerZoomFit" aria-label="התאמה למסך">התאם</button></div>
    <button type="button" id="readerFullscreen" class="reader-tool-button" aria-label="מסך מלא"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5"/></svg><span>מסך מלא</span></button>
    <div id="readerProgressBar" class="reader-progress" aria-hidden="true"></div>`;shell.appendChild(tools);tools.querySelectorAll('[data-reader-view-button]').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.readerViewButton)));$('#readerZoomOut')?.addEventListener('click',()=>shiftZoom(-1));$('#readerZoomIn')?.addEventListener('click',()=>shiftZoom(1));$('#readerZoomFit')?.addEventListener('click',()=>setZoom(1));$('#readerFullscreen')?.addEventListener('click',toggleFullscreen);$('#readerPageJump')?.addEventListener('submit',e=>{e.preventDefault();const n=Number($('#readerPageInput')?.value);if(Number.isFinite(n))navigateByControls(n)});const drawer=document.createElement('aside');drawer.id='readerToc';drawer.className='reader-toc';drawer.hidden=true;drawer.setAttribute('aria-label','תוכן עניינים');drawer.innerHTML=`<div class="reader-toc-head"><div><strong>משפט פיתגורס</strong><span>תוכן עניינים</span></div><button type="button" id="readerTocClose" aria-label="סגירת תוכן עניינים">×</button></div><label class="reader-toc-search"><span class="sr-only">חיפוש עמוד</span><input id="readerTocSearch" type="search" inputmode="search" placeholder="חיפוש מספר עמוד"></label><div id="readerTocList" class="reader-toc-list"></div>`;document.body.appendChild(drawer);$('#readerTocClose')?.addEventListener('click',()=>openToc(false));$('#readerTocSearch')?.addEventListener('input',e=>filterToc(e.target.value))}
function observeWorkbook(){const app=$('#app');if(!app)return;tocObserver?.disconnect();tocObserver=new MutationObserver(()=>{buildToc();updateProgress()});tocObserver.observe(app,{childList:true,subtree:true,attributes:true,attributeFilter:['class','data-label']});const counter=$('#counter');if(counter){counterObserver?.disconnect();counterObserver=new MutationObserver(updateProgress);counterObserver.observe(counter,{childList:true,characterData:true,subtree:true})}}
function wireKeyboard(){addEventListener('keydown',e=>{if(e.defaultPrevented||e.ctrlKey||e.metaKey||e.altKey)return;const tag=e.target?.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT'||e.target?.isContentEditable)return;if(e.key==='Home'){e.preventDefault();navigateByControls(1)}else if(e.key==='End'){e.preventDefault();navigateByControls(totalPages())}else if(e.key==='+'||e.key==='='){e.preventDefault();shiftZoom(1)}else if(e.key==='-'){e.preventDefault();shiftZoom(-1)}else if(e.key==='0'){e.preventDefault();setZoom(1)}else if(e.key.toLowerCase()==='f'){e.preventDefault();toggleFullscreen()}else if(e.key.toLowerCase()==='t'){e.preventDefault();openToc($('#readerToc')?.hidden!==false)}else if(e.key==='Escape'&&!$('#readerToc')?.hidden){openToc(false)}})}
function restoreHash(){const m=location.hash.match(/page=(\d+)/);if(!m)return;const n=Number(m[1]);if(n>1){let tries=0;const wait=()=>{if(sheetForPage(n))navigateByControls(n);else if(tries++<40)setTimeout(wait,100)};wait()}}
function bootReader(){injectUi();const savedView=safeGet(STORAGE_VIEW,'scroll');const savedZoom=Number(safeGet(STORAGE_ZOOM,'1'));setView(VALID_VIEWS.has(savedView)?savedView:'scroll',{persist:false});setZoom(ZOOMS.includes(savedZoom)?savedZoom:1,{persist:false});observeWorkbook();buildToc();wireKeyboard();restoreHash();addEventListener('resize',()=>{if(viewMode==='spread'&&matchMedia('(max-width: 899px)').matches)setView('single')},{passive:true});document.addEventListener('fullscreenchange',()=>{$('#readerFullscreen')?.classList.toggle('is-active',!!document.fullscreenElement)});setTimeout(()=>{buildToc();updateProgress()},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootReader,{once:true});else bootReader();
window.PythagorasReader={setView,setZoom,openToc,navigateTo:navigateByControls,getState:()=>({viewMode,zoom,page:currentPage(),total:totalPages()})};
})();