(()=>{'use strict';
const BLOCK='section,article,div,li,td,fieldset,figure';
const rules=[[/question|exercise|task|problem|prompt|q-main|q-sub|qrow|תרגיל|שאלה/i,'ped-question'],[/example|worked|sample|דוגמ/i,'ped-example'],[/hint|tip|note|help|foundation-note|defcard|solve-note|רמז|שים.?לב|שימו.?לב/i,'ped-hint'],[/solution|steps|פתרון/i,'ped-solution'],[/formula|equation|math|נוסח/i,'ped-formula'],[/answer|response|blank|workspace|fill|work-lines|solution-space|final-build-area|wline|mcbox|tri-check|check|תשובה/i,'ped-answer'],[/diagram|figure|geometry|triangle|shape|chart|svg|שרטוט|משולש/i,'ped-diagram'],[/helper|guide|construction|aux|grid/i,'ped-helper-line'],[/important|attention|focus|warning|חשוב/i,'ped-action']];
function signature(el){let c='';try{c=typeof el.className==='string'?el.className:(el.className?.baseVal||'')}catch{}return `${c} ${el.id||''} ${[...el.attributes||[]].map(a=>`${a.name}=${a.value}`).join(' ')}`}
function usefulContainer(el){const c=el.closest(BLOCK);if(!c||c.classList.contains('fallback'))return el;return c}
function addBySignature(root){root.querySelectorAll('*').forEach(el=>{const s=signature(el);for(const[re,cls]of rules)if(re.test(s))el.classList.add(cls)})}
function addByLabels(root){root.querySelectorAll('h1,h2,h3,h4,h5,h6,strong,b,p,span,label').forEach(el=>{const t=(el.textContent||'').replace(/\s+/g,' ').trim();if(!t||t.length>100)return;const c=usefulContainer(el);if(/^דוגמ(?:ה|א)|דוגמה פתורה/.test(t))c.classList.add('ped-example');if(/^(רמז|שים לב|שימו לב|זכרו|זכור)/.test(t))c.classList.add('ped-hint');if(/^(פתרון|דרך פתרון|שלבי פתרון|תשובות)/.test(t))c.classList.add('ped-solution');if(/^(תשובה|תשובת התלמיד)/.test(t))c.classList.add('ped-answer');if(/^(תרגיל|שאלה)\s*\d*/.test(t))c.classList.add('ped-question');if(/^(חשוב|שימו לב)/.test(t))c.classList.add('ped-action')})}
function addLiveWorkbookRoles(root){root.querySelectorAll('.question-block').forEach(e=>e.classList.add('ped-question-group'));root.querySelectorAll('.q,.q-main,.q-sub,.qrow,.final-build-task').forEach(e=>e.classList.add('ped-question'));root.querySelectorAll('.foundation-note,.defcard,.pyt-solve-note').forEach(e=>e.classList.add('ped-concept'));root.querySelectorAll('.foundation-card,.tri-cell,.figure,.pyt-diagram-frame,.cur-fig,.visual-container,.figrow').forEach(e=>e.classList.add('ped-card'));root.querySelectorAll('.foundation-fill,.pyt-final-answer,.work-lines,.solution-space,.final-build-area,.wline,.mcbox,.tri-check,.check').forEach(e=>e.classList.add('ped-answer'));root.querySelectorAll('.pyt-solutions,.pyt-solution').forEach(e=>e.classList.add('ped-solution'));root.querySelectorAll('.bullet-large,.bullet-small').forEach(e=>e.classList.add('ped-bullet'));root.querySelectorAll('.gz-footer').forEach(e=>e.classList.add('ped-footer'));root.querySelectorAll('.chapter-bar').forEach(e=>e.classList.add('ped-section-title'))}
function addStructural(root){root.querySelectorAll('h1,.page-title').forEach(e=>e.classList.add('ped-page-title'));root.querySelectorAll('h2,.chapter-bar').forEach(e=>e.classList.add('ped-section-title'));root.querySelectorAll('h3,h4,h5,h6,.page-subtitle').forEach(e=>e.classList.add('ped-subtitle'));root.querySelectorAll('svg').forEach(svg=>usefulContainer(svg).classList.add('ped-diagram'));root.querySelectorAll('math,.math,math-field,[data-math],[class*="formula" i],[class*="equation" i]').forEach(e=>usefulContainer(e).classList.add('ped-formula'));root.querySelectorAll('input,textarea,[contenteditable="true"]').forEach(e=>usefulContainer(e).classList.add('ped-answer'));addLiveWorkbookRoles(root)}
function normalize(root){addStructural(root);addBySignature(root);addByLabels(root);root.querySelectorAll('.ped-example.ped-hint').forEach(e=>e.classList.remove('ped-example'))}
function audit(scope){return[...scope.querySelectorAll('.fallback')].map((p,i)=>({page:p.dataset.localPageId||String(i+1).padStart(3,'0'),source:p.dataset.sourceFile||'',questions:p.querySelectorAll('.ped-question').length,concepts:p.querySelectorAll('.ped-concept').length,examples:p.querySelectorAll('.ped-example').length,hints:p.querySelectorAll('.ped-hint').length,solutions:p.querySelectorAll('.ped-solution').length,formulas:p.querySelectorAll('.ped-formula').length,answers:p.querySelectorAll('.ped-answer').length,diagrams:p.querySelectorAll('.ped-diagram').length,tables:p.querySelectorAll('table').length,svgs:p.querySelectorAll('svg').length}))}
function apply(scope=document){if(scope.matches?.('.fallback'))normalize(scope);scope.querySelectorAll?.('.fallback').forEach(normalize);window.__PYTHAGORAS_DESIGN_AUDIT__=audit(document);return window.__PYTHAGORAS_DESIGN_AUDIT__}
let queued=false;function queueApply(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;apply(document)})}const observer=new MutationObserver(ms=>{if(ms.some(m=>[...m.addedNodes].some(n=>n.nodeType===1&&(n.matches?.('.fallback')||n.querySelector?.('.fallback')))))queueApply()});function start(){apply(document);observer.observe(document.documentElement,{childList:true,subtree:true})}window.PythagorasBookDesign={apply,audit,observer,start};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();